### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by jvanderwee** [bitrise-steplib/steps-fastlane#10]
As Fastlane now has Android tools, what needs to be changed in order for this step to appear when 'Show only Steps supported by platform?' is checked for an Android project?

**Comment by viktorbenei** [comment]
Just have to be added as a `project_type_tag`: https://github.com/bitrise-io/steps-fastlane/blob/master/step.yml#L11

One more thing can be done, `fastlane` is pre-installed on the OS X stacks but not on the Linux/Android stacks. It's a simple `gem install`, but we're not sure in which layer it should be included (base, android or android-ndk -> https://github.com/bitrise-docker). Probably should be in the Android image, as it's main use case is related to Android - the "base" image is intended to be used for web, and other projects which do not depend on / do not require the Android tools. What do you think?

**Comment by jvanderwee** [comment]
Added project type tag: https://github.com/bitrise-io/steps-fastlane/pull/11

Pre-installing in the Android image sounds best: https://github.com/bitrise-docker/android/pull/9

**Comment by viktorbenei** [comment]
Published in v2.1.3 - thanks!
