### ISSUE TITLE
Fastlane breaks on version 2.212.1, bundled inside 3.5.2 step version

### ISSUE THREAD

**Issue by miguelfs** [bitrise-steplib/steps-fastlane#105]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 3.5.2
- Is the issue reproducible with the latest version? YES 
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

A bug emerged at previous versions of fastlane. It has been well reported in the last 12h in here:

- https://github.com/fastlane/fastlane/issues/21819

This issue is affecting the Fastlane step at Bitrise, because the current 3.5.2 step uses the 2.212.1 version.

The most reported fix is to upgrade to 2.219.0 version.

### Bitrise info

<details>
  <pre>
Determine desired Fastlane version
Gem lockfile defined Fastlane version: 2.212.1
Gem lockfile defined bundler version: 2.1.4
Checking selected Ruby version
$ asdf "current" "ruby"
ruby            3.2             /Users/vagrant/.tool-versions
Unrecognized Ruby version: [Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]]
Active Ruby version: `DidYouMean::SPELL_CHECKERS.merge!(error_name
Install bundler
$ gem "install" "bundler" "--no-document" "-v" "2.1.4" "--force"
[DEBUG] POST https://step-analytics.bitrise.io/track
Successfully installed bundler-2.1.4
1 gem installed
$ asdf "reshim" "ruby"
[...]
|                                      Lane Context                                      |
+------------------------------------+---------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                               |
| PLATFORM_NAME                      | ios                                               |
| LANE_NAME                          | SENSITIVE_DATA                                          |
| SIGH_PROFILE_TYPE                  | SENSITIVE_DATA                                         |
| MATCH_PROVISIONING_PROFILE_MAPPING | {SENSITIVE_DATA} |
| IPA_OUTPUT_PATH                    | SENSITIVE_DATA                 |
| XCODEBUILD_ARCHIVE                 | SENSITIVE_DATA             |
| DSYM_OUTPUT_PATH                   |SENSITIVE_DATA        |
+------------------------------------+---------------------------------------------------+
[19:10:17]: A parameter has an invalid value - 'prices' is not a valid relationship name
+------+----------------------+-------------+
|             fastlane summary              |
+------+----------------------+-------------+
| Step | Action               | Time (in s) |
+------+----------------------+-------------+
| 1    | default_platform     | 0           |
| 2    | match                | 1           |
| 3    | build_app            | 35          |
| 💥   | upload_to_testflight | 0           |
+------+----------------------+-------------+
[19:10:17]: fastlane finished with errors

  </pre>
</details>

### Steps to reproduce

1. Attempt to upload to App Store using Testflight.

**Comment by banshchikov** [comment]
Same here 👍

**Comment by abdymm** [comment]
same here 👍

**Comment by bevan667** [comment]
same here..

**Comment by abdymm** [comment]
oh while waiting for Bitrise team to update their Fastlane step, as a temporary solution you can just update your fastlane in your gemfile by using the latest version `2.219.0`

`gem "fastlane", '2.219.0'`

then do `bundle install` , and try to deploy, mines works now @banshchikov @bevan667

**Comment by banshchikov** [comment]
@abdymm thanks! it solved the issue
