### ISSUE TITLE
Bundler install creates the .bundle folder in the working directory

### ISSUE THREAD

**Issue by GabrielCartier** [bitrise-steplib/steps-fastlane#15]
When running the fastlane step, it will automatically check for a Gemfile to run bundle install on it prior to executing fastlane.

The problem is that this creates a .bundle folder in the root of the project which can cause the git repository to not be clean.

I am not sure why it's like that or if you can actually change the folder where the gems are installed. In any case, there is a command in fastlane to do it. 

In my case, the problem is that I want bitrise to bump versions when doing releases, but I can't since there are some extra uncommitted files.

**Comment by viktorbenei** [comment]
Hi,

The step checks for a Gemfile in your fastlane base dir, and if it finds one it'll `bundle install` and use that.

The solution right now is to add the `.bundle` folder to your `.gitignore` file. This is a best practice if you have a `Gemfile` in your repo, as `bundle install` can generate the `.bundle` folder on any Mac/PC when you run `bundle install`.

**Comment by viktorbenei** [comment]
I'll close this issue, but feel free to ask any question, if required we'll reopen it / mark as a bug.

**Comment by brandtdaniels** [comment]
> This is a best practice if you have a Gemfile in your repo, as bundle install can generate the .bundle folder on any Mac/PC when you run bundle install.

Do you have a reference for this remark? I have never seen this file generated until I started to experiment with Bitrise.

**Comment by brandtdaniels** [comment]
I think I found it: https://bundler.io/v1.6/deploying.html
