### ISSUE TITLE
fastlane step fails

### ISSUE THREAD

**Issue by snydersaurus** [bitrise-steplib/steps-fastlane#16]
Added fastlane as the last step in my build on Bitrise.io-- fails with the following:

Fastlane version:
$ bundle exec fastlane --version
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
Gem::LoadError: fastlane is not part of the bundle. Add it to Gemfile.
  /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.1/lib/bundler/rubygems_integration.rb:322:in `block in replace_gem'
  /usr/local/bin/fastlane:22:in`<top (required)>'

**Comment by viktorbenei** [comment]
TL;DR; If you use a Gemfile you should specify fastlane there as well

Longer version: if you use a `Gemfile` in your repo, most of the Bitrise Steps expect that you'll list your Ruby dependencies there (as that's the purpose of the `Gemfile`). Especially in case of `fastlane`, you most likely want to lock/specify which version should be used, as `fastlane` is updated quite frequently.
