### ISSUE TITLE
Not installing via Gemfile

### ISSUE THREAD

**Issue by ky1ejs** [bitrise-steplib/steps-fastlane#17]
We recently added a `Gemfile` to our iOS project, and I noticed I needed to add Fastlane to it to be able to use this step.

The small problem I have with this is that we need to install all the gems that we use for other parts of testing that aren't used when we use Fastlane. It seems slightly unnecessary to install all the gems just to use Fastlane.

I guess that this approach of using the `Gemfile` was taken to give a mechanism of depending of a specific version of Fastlane? Which makes sense. But perhaps this should be a step variable, rather than using the `Gemfile`?

What do you think? Would you be open to this changing to a step variable? I can PR if so 😊.

**Comment by ky1ejs** [comment]
Maybe [Bundler groups](http://bundler.io/groups.html) could be used in some way?

**Comment by viktorbenei** [comment]
Sure @kylejm , we'd be open to do that. I'd prefer if we would instead add a "use Gemfile" input field, which, if you set to the Gemfile's path, that would be used, otherwise no Gemfile will be used.

But for backwards compatibility maybe a simple "on/off" input would be better.. WDYT - also @godrei ;)

**Comment by viktorbenei** [comment]
Bundler groups could also work, but that still requires manual config for the step, to specify which group to install or not to install - I think that's a bit out of scope for this step, too much manual config / internal knowledge required (most of the users who use fastlane are not familiar with how Gemfiles work, at least it seems like that based on the support tickets)

**Comment by ky1ejs** [comment]
Our requirements have no changed and we really like specifically setting the Fastlane version via the Gemfile.lock. Shall I close? 😄

**Comment by viktorbenei** [comment]
We now have a common code we use in a couple of other steps which checks the Gemfile/.lock whether the target gem is included in the file, and only uses `bundle install` if the tool is part of the Gemfile/.lock

I think that could be added here, and that would fix the issue you reported, so we should leave this issue open for now ;)

**Comment by godrei** [comment]
Hi @kylejm ,
new version [2.3.0](https://github.com/bitrise-io/steps-fastlane/releases/tag/2.3.0) is released, this version uses bundler to install Fastlane only, if Gemfile.lock contains fastlane gem dependency.

The new version will be available in the setplib in ~ 20min.

I'll close this issue, but if you need more info/help just let us know and we'll reopen it!
