### ISSUE TITLE
Unable to run action when options parameter contain spaces

### ISSUE THREAD

**Issue by chrisfullscreen** [bitrise-steplib/steps-fastlane#18]
Hi - it looks like the fastlane action step is not able to run properly when there is a space in the input parameter:

fastlane itunesupload ipapath:'/var/User/temporary/My Example.ipa'

It will error out and said 

> cannot find lane 'itunesupload Example.ipa'

**Comment by viktorbenei** [comment]
Thanks for reporting this issue!

Could you please include the full log of this step from your build log? Just this step's log, but including the step header and footer too. It'd help a lot!

**Comment by chrisfullscreen** [comment]
Here are the logs

> +------------------------------------------------------------------------------+
> | (7) iTunesConnect Upload                                                     |
> +------------------------------------------------------------------------------+
> | id: fastlane                                                                 |
> | version: 2.2.0                                                               |
> | collection: https://github.com/bitrise-io/bitrise-steplib.git                |
> | toolkit: bash                                                                |
> | time: 2016-10-07T18:10:30-07:00                                              |
> +------------------------------------------------------------------------------+
> |                                                                              |
> $ cd /Users/vagrant/git
> 
>  (i) No Gemfile found - using system installed fastlane ...
>  (i) Updating fastlane ...
> $ gem install fastlane --no-document
> Successfully installed fastlane-1.105.0
> 1 gem installed
> 
> Fastlane version:
> $ fastlane --version
> fastlane 1.105.0
> 
> Run fastlane:
> $ fastlane itunesupload ipapath:'/Users/vagrant/deploy/My Sample.ipa' 
> [18:10:37]: -------------------------------------------------
> [18:10:37]: --- Step: Verifying required fastlane version ---
> [18:10:37]: -------------------------------------------------
> [18:10:37]: Your fastlane version 1.105.0 matches the minimum requirement of 1.104.0  ✅
> [18:10:37]: ------------------------------
> [18:10:37]: --- Step: default_platform ---
> [18:10:37]: ------------------------------
> [18:10:37]: Variable Dump:
> [18:10:37]: {:DEFAULT_PLATFORM=>:ios}
> [18:10:37]: Could not find lane 'itunesupload Sample.ipa''. Available lanes: ios bumpversion, ios itunesupload, ios pushversion
> 
> +------+-------------------------------------+-------------+
> |                     fastlane summary                     |
> +------+-------------------------------------+-------------+
> | Step | Action                              | Time (in s) |
> +------+-------------------------------------+-------------+
> | 1    | Verifying required fastlane version | 0           |
> | 2    | default_platform                    | 0           |
> +------+-------------------------------------+-------------+
> 
> [18:10:37]: fastlane finished with errors
> 
> [!] Could not find lane 'itunesupload Sample.ipa''. Available lanes: ios bumpversion, ios itunesupload, ios pushversion
> |                                                                              |
> +----+--------------------------------------------------------------+----------+
> | 🚫  | iTunesConnect Upload (exit code: 1)                          | 8.6 sec  |
> +----+--------------------------------------------------------------+----------+
> | Issue tracker: https://github.com/bitrise-io/steps-fastlane/issues           |
> | Source: https://github.com/bitrise-io/steps-fastlane                         |
> +----+--------------------------------------------------------------+----------+

**Comment by godrei** [comment]
Hi @chrisfullscreen ,
we released a new version [2.3.0](https://github.com/bitrise-io/steps-fastlane/releases/tag/2.3.0), it will `shell split` the lane input's value, to properly pass these params to fastlane command.

The new version will be available in the steplib in ~20min.

I'll close this issue, but if you need more info/help just let us know and we'll reopen it!
