### ISSUE TITLE
Please update to Fastlane 2.33.0

### ISSUE THREAD

**Issue by ofairfoul** [bitrise-steplib/steps-fastlane#29]
The iTunes pilot step is no longer working due to new iTC
fastlane/fastlane#9238
This fastlane release has the fix
https://github.com/fastlane/fastlane/releases/tag/2.33.0

**Comment by viktorbenei** [comment]
Upgrading fastlane:

From the step's description: https://github.com/bitrise-io/steps-fastlane/blob/master/step.yml#L7

> If `Gemfile` exists in the `work_dir` directory, fastlane will be used by `bundle install` && `bundle exec`.
> Otherwise the system installed `fastlane` version will be used.

And if you don't have a `Gemfile` (and `Gemfile.lock`) in your repo, specifying the fastlane version you want to use, you can use the `update_fastlane` / **Should update fastlane gem before run?** input option of this step (https://github.com/bitrise-io/steps-fastlane/blob/master/step.yml#L52).

If you'd have any questions please let us know!
