### ISSUE TITLE
Android Build/Upload Issue

### ISSUE THREAD

**Issue by RuanFluid** [bitrise-steplib/steps-fastlane#30]
Getting this error:

undefined method `timeout_sec=' for #<Google::Apis::RequestOptions:0x00561553e6b338>

**Comment by viktorbenei** [comment]
Can you please create an issue on their issue tracker? https://github.com/fastlane/fastlane

Actually, it seems there already is an issue report: https://github.com/fastlane/fastlane/issues/9501

Based on the comments it should now work if you upgrade to the latest fastlane version.
