### ISSUE TITLE
IDEA: Add `skip Gemfile` input parameter

### ISSUE THREAD

**Issue by oronbz** [bitrise-steplib/steps-fastlane#35]
Hi there!

We do use `Gemfile` for running `fastlane` locally, but, we do want to save those expensive `bundle install` seconds when running on `bitrise`.

Is there any possibility of adding such a parameter which skips `bundle install` even if `Gemfile` exists?

I would've make a pull request myself, but I haven't find a way of running custom steps in bitrise workflow that target my own repository.

**Comment by viktorbenei** [comment]
Hi @oronbz 

Workaround: have a Script which deletes the Gemfile/.lock or just moves/renames it.

> I would've make a pull request myself, but I haven't find a way of running custom steps in bitrise workflow that target my own repository.

OR would be awesome, and it's actually fairly simple to switch to a custom/to your own step repo: http://devcenter.bitrise.io/bitrise-cli/steps/#step-referenceid-format - specifically the `git::` style, e.g.:

```
- git::https://github.com/bitrise-io/steps-script.git@master:
```

which will git clone the `master` branch of `https://github.com/bitrise-io/steps-script.git`

If you'd have any questions just let me know! ;)
