### ISSUE TITLE
Fastlane error: unkown ruby installation type

### ISSUE THREAD

**Issue by aindeev** [bitrise-steplib/steps-fastlane#38]
We started seeing this issue today (nov 17, 2018)

```
Update system installed Fastlane
Failed to create command model, error: unkown ruby installation type
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | fastlane@2.3.12 (exit code: 1)                                | 3.70 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-fastlane/issues           |
| Source: https://github.com/bitrise-io/steps-fastlane    
```

Any ideas?

**Comment by kevinmun** [comment]
Same here

**Comment by yamataku29** [comment]
Same here

**Comment by jinthagerman** [comment]
Same here

**Comment by tamasbazs** [comment]
Hi there,
We are sorry for the inconvenience caused! Could you try running your build using our Hybrid stack? I notified our infra team, but finding a fix would take a bit more time than the ideal, so this could be a workaround for now.

**Comment by jinthagerman** [comment]
I managed to workaround it using a Ruby script with gemfile step. Copied my gemfile in and then just put `fastlane beta` in the script in backticks.

**Comment by jinthagerman** [comment]
Hybrid stack is also working, thanks!

**Comment by yamataku29** [comment]
Thank you for your reply!
I got build succeed when I did change to Hybrid stack.

2018年11月19日(月) 6:44 Jin Budelmann <notifications@github.com>:

**Comment by bitce** [comment]
Hi guys, all stacks should be working by now! Thanks for the patience.

**Comment by Aw79** [comment]
Had the same problem.
Works for me again, thanks!
