### ISSUE TITLE
Is there a way to specify version of fastlane?

### ISSUE THREAD

**Issue by rlam3** [bitrise-steplib/steps-fastlane#39]
Is there a way to specify version of fastlane and github release branch/commit?

**Comment by bitce** [comment]
HI @rlam3! Please check this thread: https://discuss.bitrise.io/t/how-to-use-a-specific-version-of-fastlane/1001 

And if possible clarify what you mean by specifying GitHub release branch/commit, you can, of course, adjust which branch to build or what commit to trigger your builds with, but I'm not entirely sure what you mean!

**Comment by rlam3** [comment]
@bitce I'm looking to update fastlane to the master branch / specific git commit to test different environments source. I was wondering if you have a way in steps-fastlane to allow for this type of settings in workflow. Currently this step allows us to grab the latest version but I need the version that is on master branch with changes already made which is not in release yet. The master branch has changes that are 1 month ahead already.

I took a look at my gemfile and saw I could do the following however it is not working and still repeatedly only grabs version 2.108.0.... Not the master branch, I tried to find alternatives like specify even `nightly` option so we can grab latest master builds to be used in our ci/cd, but I don't know where in this fastlane step we could even call on that option. It seems there is no way to configure it.

```rb
source "https://rubygems.org"

gem "fastlane", :git => 'git@github.com:fastlane/fastlane.git', :branch => 'master'
```

Thanks!

**Comment by fehersanyi-bitrise** [comment]
Hy @rlam3!
I have an idea on this like:
set fastlane to not update the version
and put a script step in the workflow(s) with the content @bitce linked with an env var check like

if $BITRISE_GIT_BRACH == master {
install latest
} else {
install specific version
}
or something like this at the first glance.
