### ISSUE TITLE
Plugin installs really old version of Fastlane, update doesn't work

### ISSUE THREAD

**Issue by ktchernov** [bitrise-steplib/steps-fastlane#41]
First time running this plugin, running a step that works fine from my own Mac with fastlane v2.116.0 fails with multiple errors.

In the build logs I've spotted this warning being printed by fastlane:

```
#######################################################################
# fastlane 2.116.0 is available. You are on 2.98.0.
# You should use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################
```

In Workflow, I have the plugin setting "Should update fastlane gem before run? Insert variable" set to true.

Looks like the update is not working.

**Comment by fehersanyi-bitrise** [comment]
Hy @ktchernov 

Could it be that you hardcoded the fastlane version somewhere in a fastfile or podfile?

**Comment by ktchernov** [comment]
No, Fastlane is not listed in the Podfile, and the version is not hardcoded anywhere else.

**Comment by ktchernov** [comment]
Doh. Yep, hardcoded in the Gemfile lock. Thank you!
