### ISSUE TITLE
Feature request: expose fastlane env variables to Bitrise

### ISSUE THREAD

**Issue by gaguirre** [bitrise-steplib/steps-fastlane#45]
I'd like to access typical fastlane environment variables (e.g. build path) from another Bitrise step (e.g. "Deploy to Bitrise" using the fastlane build path).

I know it can be done using envman and that it can't be known which variables will be available (without evaluating the _lane_ that will be executed), but maybe all possible env variables can be exposed with a note that they could be empty.

Have you considered it?

**Comment by fehersanyi-bitrise** [comment]
Hello @gaguirre , Could you please make your feature request here? so the appropriate team can follow it up 🙃 https://discuss.bitrise.io/c/feature-request
