### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by Workshed** [bitrise-steplib/steps-fastlane#48]
The [link given](https://devcenter.bitrise.io/getting-started/signing-up/connecting-apple-dev-account/) when hitting this line results in a 404 error, has this moved?

https://github.com/bitrise-steplib/steps-fastlane/blob/a6e1b28b292e0b7ce826dcc9c032f59ef95bd124/main.go#L110

Thanks!

**Comment by bitce** [comment]
Hi!

Thanks for catching this, yes, it was moved to this location: https://devcenter.bitrise.io/getting-started/connecting-apple-dev-account/

**Comment by Workshed** [comment]
No problem. Just so you're aware, some of your docs also reference the old link: https://devcenter.bitrise.io/getting-started/connecting-apple-dev-account/
<img width="758" alt="Screenshot 2019-06-19 at 08 26 20" src="https://user-images.githubusercontent.com/422196/59745140-0cc6f700-926c-11e9-8467-420e9ecd68b7.png">

**Comment by godrei** [comment]
Hi @Workshed , link fixed in the latest version [2.7.2](https://github.com/bitrise-steplib/steps-fastlane/releases/tag/2.7.2).
I'll close this issue, but if you need more info/help just open a new issue!
