### ISSUE TITLE
Rename to "Work directory" to "Working directory"

### ISSUE THREAD

**Issue by hokster7** [bitrise-steplib/steps-fastlane#5]
For consistency with other steps, e.g. https://github.com/bitrise-io/steps-carthage

**Comment by viktorbenei** [comment]
Good point, we'll change the title of the input, thank you for the suggestion!

**Comment by godrei** [comment]
Fixed in version 2.1.2 (https://github.com/bitrise-io/steps-fastlane/releases/tag/2.1.2).
Thanks @fatuhoku !
