### ISSUE TITLE
Specify Gemfile and Gemfile.lock locations?

### ISSUE THREAD

**Issue by henriquenfaria** [bitrise-steplib/steps-fastlane#52]
Is the fastlane step only searching for the Gemfile and Gemfile.lock inside the working directory I set in the UI? In my setup I set the working dir to ./fastlane but both Gemfile files are living inside the root folder of my project.

**Comment by henriquenfaria** [comment]
I fixed my issue after setting the working dir to my project's root

**Comment by bitce** [comment]
Hi @henriquenfaria,

Glad to hear that you were able to work this out 🙂
