### ISSUE TITLE
[M1 stack] Failed to install Step dependencies - gem install bundler failed

### ISSUE THREAD

**Issue by AleksanderMaj** [bitrise-steplib/steps-fastlane#96]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 3.4.2
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)?  NO

### Bitrise info

- Build URL: [Build URL](https://app.bitrise.io/build/a58d1741-7c22-47b6-9471-7d134ca0d090)
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Log:
```
Failed to install Step dependencies:
  command failed with exit status 1 (gem "install" "bundler" "--no-document" "-v" "2.4.12" "--force"):
```
Full log in details:
<details>
  <pre>
Inputs:
- work_dir: ./DonkeyRepublic
- lane: develop force:true
- connection: automatic
- apple_id: <unset>
- password: <unset>
- app_password: <unset>
- api_key_path: <unset>
- api_issuer: <unset>
- update_fastlane: false
- verbose_log: true
- enable_cache: true
- GEM_HOME: <unset>
- BITRISE_BUILD_URL: https://app.bitrise.io/build/a58d1741-7c22-47b6-9471-7d134ca0d090
- BITRISE_BUILD_API_TOKEN: *****
Expand WorkDir
Expanded WorkDir: /Users/vagrant/git/DonkeyRepublic
Checking rbenv version
$ rbenv "versions"
  system
  2.6.9
  2.7.2
  2.7.5
  2.7.6
  3.0.0
  3.0.3
* 3.1.0 (set by /Users/vagrant/git/DonkeyRepublic/.ruby-version)
  3.1.3
  3.2.1
Reading Apple Developer Portal authentication data
[DEBUG] GET https://app.bitrise.io/build/a58d1741-7c22-47b6-9471-7d134ca0d090/apple_developer_portal_data.json
Bitrise Apple Developer Connection with Apple ID found.
Determine desired Fastlane version
Gem lockfile defined Fastlane version: >= 2.0
Gem lockfile defined bundler version: 2.4.12
Failed to check active Ruby version: executing command failed (bundle "_2.4.12_" "exec" "ruby" "--version"): exec: Stdout already set
Output: 
Install bundler
$ gem "install" "bundler" "--no-document" "-v" "2.4.12" "--force"
/opt/homebrew/Cellar/rbenv/1.2.0/libexec/rbenv-exec: /Users/vagrant/.rbenv/versions/3.1.0/bin/gem: /Users/vagrant/ruby31/bin/ruby: bad interpreter: No such file or directory
/opt/homebrew/Cellar/rbenv/1.2.0/libexec/rbenv-exec: line 47: /Users/vagrant/.rbenv/versions/3.1.0/bin/gem: Undefined error: 0
Failed to install Step dependencies:
  command failed with exit status 1 (gem "install" "bundler" "--no-document" "-v" "2.4.12" "--force"):
    check the command's output for details
  </pre>
</details>

### Steps to reproduce

1. Run fastlane step on M1 stack

**Comment by tzuhan-bitrise** [comment]
Hi @AleksanderMaj, sorry for the inconvenience caused.
You can use rbenv to switch the ruby version to 3.1.3 or higher, or downgrade to 3.0.0 and this issue should be solved.

**Comment by AleksanderMaj** [comment]
@tzuhan-bitrise, thanks a lot. I'll try next week and let you know

**Comment by AleksanderMaj** [comment]
Yup, the problem is gone now.
