### ISSUE TITLE
Fastlane fails on latest verison of Ruby 3

### ISSUE THREAD

**Issue by geetotes** [bitrise-steplib/steps-fastlane#99]
### Troubleshooting

- [ x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 3.4.3
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE 

### Bitrise info

- [Build URL](https://app.bitrise.io/build/a4762ceb-fac9-4ac2-8878-38ff6a3c9b80)
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES_
- Log:
```

Failed to install Step dependencies:
  command failed with exit status 5 (bundle "_2.1.4_" "install" "--jobs" "20" "--retry" "5"):
    check the command's output for details
Failed to install Step dependencies:
  command failed with exit status 5 (bundle "_2.1.4_" "install" "--jobs" "20" "--retry" "5"):
    check the command's output for details
```

<details>
  <pre>
+------------------------------------------------------------------------------+

| (2) fastlane                                                                 |
+------------------------------------------------------------------------------+
| id: fastlane                                                                 |
| version: 3.4.3                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2023-07-17T20:15:10Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Inputs:
- work_dir: ./capacitor/ios/App
- lane: build
- connection: automatic
- apple_id: <unset>
- password: <unset>
- app_password: <unset>
- api_key_path: <unset>
- api_issuer: <unset>
- update_fastlane: true
- verbose_log: false
- enable_cache: true
- GEM_HOME: <unset>
- BITRISE_BUILD_URL: https://app.bitrise.io/build/a4762ceb-fac9-4ac2-8878-38ff6a3c9b80
- BITRISE_BUILD_API_TOKEN: *****
Expand WorkDir
Expanded WorkDir: /Users/vagrant/git/capacitor/ios/App
Checking rbenv version
$ rbenv "versions"
  system
  2.6.9
  2.7.2
  2.7.5
  2.7.6
  3.0.0
  3.0.3
  3.1.0
  3.1.3
  3.1.4
  3.2.1
* 3.2.2 (set by /Users/vagrant/.rbenv/version)
Reading Apple Developer Portal authentication data
Bitrise Apple Developer Connection with API key found
Determine desired Fastlane version
Gem lockfile defined Fastlane version: 2.182.0
Gem lockfile defined bundler version: 2.1.4
Failed to check active Ruby version: command failed with exit status 1 (bundle "_2.1.4_" "exec" "ruby" "--version"): check the command's output for details
Output: /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems.rb:263:in `find_spec_for_exe': can't find gem bundler (= 2.1.4) with executable bundle (Gem::GemNotFoundException)
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems.rb:282:in `activate_bin_path'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/bin/bundle:25:in `<main>'
Install bundler
$ gem "install" "bundler" "--no-document" "-v" "2.1.4" "--force"
Successfully installed bundler-2.1.4
1 gem installed
$ rbenv "rehash"
Install Fastlane with bundler
$ bundle "_2.1.4_" "install" "--jobs" "20" "--retry" "5"
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Fetching gem metadata from https://rubygems.org/........
google-api-client-0.38.0 requires ruby version ~> 2.4, which is incompatible
with the current version, ruby 3.2.2p53
Failed to install Step dependencies:
  command failed with exit status 5 (bundle "_2.1.4_" "install" "--jobs" "20" "--retry" "5"):
    check the command's output for details
Failed to install Step dependencies:
  command failed with exit status 5 (bundle "_2.1.4_" "install" "--jobs" "20" "--retry" "5"):
    check the command's output for details
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | fastlane (Failed)                                             | 9.63 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-fastlane/issues           |
| Source: https://github.com/bitrise-io/steps-fastlane                         |
+---+---------------------------------------------------------------+----------+
  </pre>
</details>

### Steps to reproduce

1. Run fastlane build step with M1 on Xcode 14.1.x, on macOS 13.2 (Ventura)

**Comment by sarojraut** [comment]
I am facing the same issue from today.

**Comment by geetotes** [comment]
My current workaround is a script step to run
```
asdf install ruby 2.6.9
asdf global ruby 2.6.9
```
